### ISSUE TITLE
Error on test dataset

### ISSUE THREAD

**Issue by jsoghigian** [jeffersonfparil/compare_genomes#11]
Hi,

So, I did not have access to PANTHER 17 files, and so I did modify files to PANTHER 18. It is possible this is the cause somehow, but I am skeptical because of where the error occurs.

The pipeline completes Orthofinder, as far as I can tell, but fails after that. I see this error message in command.err :
```
Traceback (most recent call last):
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/orthofinder", line 7, in <module>
    main(args)
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/__main__.py", line 1778, in main
    GetOrthologues(speciesInfoObj, options, prog_caller)
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/__main__.py", line 1540, in GetOrthologues
    orthologues.OrthologuesWorkflow(speciesInfoObj.speciesToUse, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/orthologues.py", line 999, in OrthologuesWorkflow
    spTreeFN_ids, qSTAG = db.RunAnalysis(userSpeciesTree == None)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/orthologues.py", line 481, in RunAnalysis
    stag.Run_ForOrthoFinder(files.FileHandler.GetOGsTreeDir(), files.FileHandler.GetWorkingDirectory_Write(), self.ogSet.seqsInfo.speciesToUse, spTreeFN_ids)
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/stag.py", line 262, in Run_ForOrthoFinder
    ProcessTrees(dir_in, dir_matrices, dir_trees_out, gene_to_species, qVerbose=False, qForOF=True)
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/stag.py", line 191, in ProcessTrees
    t = tree.Tree(fn)
        ^^^^^^^^^^^^^
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/tree.py", line 221, in __init__
    read_newick(newick, root_node = self, format=format)
  File "/work/soghigian_lab/apps/conda/envs/compare_genomes/bin/scripts_of/newick.py", line 208, in read_newick
    nw = open(newick, 'rU').read()
         ^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

```

**Comment by jeffersonfparil** [comment]
Hi @jsoghigian,
I think orthofinder failed to run successfully. Can you please show me the other error messages?
Also, the older versions of PantherDB are still accessible via ftp, e.g. `http://data.pantherdb.org/ftp/panther_library/17.0/PANTHER17.0_hmmscoring.tgz`.

**Comment by jsoghigian** [comment]
Hi @jeffersonfparil 

I'll try the test with the panther 17.0 files when I can, but in the mean time -
Orthofinder has many directories, including those I'd expect with OrthoFinder (e.g. Orthologues, Comparative Genomics Stats).  The Working Directory has 3 dirs in it: 
The pipeline reported OrthoFinder had finished, but it maybe didn't... I attached the .command.log file from OrthoFinder I think (sorry, I may have the wrong files - let me know if there's a specific command file I should look for the log for).

[log_to_upload_command.log](https://github.com/jeffersonfparil/compare_genomes/files/13241632/log_to_upload_command.log)

The pipeline did error at every step after orthofinder with the inability to find the right files etc (can send those logs if needed, but they all are basically saying they can't find alignments/sequences).

**Comment by jeffersonfparil** [comment]
Yes you're correct. The error was in orthofinder where it failed to build its own trees. The downstream modules will require the tree built with iqtree though (exactly because of this eventuality). Let me know if the problem persists with PantherDB v17.
